# ***Tarea 09*** 
### **Nombre:** Lenin Vasquez
Github: https://github.com/Lenin5592002/Metodos

# **Ejercicio 1**
## Para cada uno de los siguientes sistemas lineales, obtenga, de ser posible, una solución con métodos gráficos.
## Explique los resultados desde un punto de vista geométrico.

## a. Sistema con Solución Única
**Sistema:**
$$
\begin{cases}
x_1 + 2x_2 = 0 \\
x_1 - x_2 = 0
\end{cases}
$$

* **Análisis:** Ambas ecuaciones son rectas que pasan por el origen $(0,0)$.
    * La primera recta tiene pendiente negativa ($x_2 = -0.5x_1$).
    * La segunda recta tiene pendiente positiva ($x_2 = x_1$).
* **Interpretación Geométrica:** Las dos rectas se cortan (intersecan) en un único punto exacto.
* **Solución:** $x_1 = 0, x_2 = 0$.

## b. Sistema Inconsistente (Paralelas)
**Sistema:**
$$
\begin{cases}
x_1 + 2x_2 = 3 \\
-2x_1 - 4x_2 = 6
\end{cases}
$$

* **Análisis:**
    * Ecuación 1: $x_1 + 2x_2 = 3$.
    * Ecuación 2: Si dividimos por $-2$, obtenemos $x_1 + 2x_2 = -3$.
* **Interpretación Geométrica:** Esto implica que la cantidad $x_1 + 2x_2$ debe ser igual a $3$ y a $-3$ simultáneamente, lo cual es imposible. Gráficamente, son dos rectas con la misma pendiente (paralelas) pero desplazadas (distinto intercepto). Nunca se tocan.
* **Solución:** No tiene solución.

## c. Sistema Sobredeterminado (Sin solución común)
**Sistema:**
$$
\begin{cases}
2x_1 + x_2 = -1 \\
x_1 + x_2 = 2 \\
x_1 - 3x_2 = 5
\end{cases}
$$

* **Análisis:** Tenemos 3 rectas en el plano.
    * Si resolvemos las dos primeras, se cruzan en $(-3, 5)$.
    * Si probamos este punto en la tercera ecuación: $-3 - 3(5) = -18$, lo cual no es igual a $5$.
* **Interpretación Geométrica:** Las tres rectas se cruzan de dos en dos formando un triángulo, pero no existe un solo punto donde se crucen las tres al mismo tiempo.
* **Solución:** No tiene solución.

## d. Sistema en 3D (Planos)
**Sistema:**
$$
\begin{cases}
2x_1 + x_2 + x_3 = 1 \\
2x_1 + 4x_2 - x_3 = -1
\end{cases}
$$

* **Análisis:** Al tener 3 variables ($x_1, x_2, x_3$), cada ecuación representa un **plano** en el espacio tridimensional, no una recta.
* **Interpretación Geométrica:** Dos planos no paralelos en el espacio se intersecan formando una **línea recta**.
* **Solución:** Tiene **infinitas soluciones** (todos los puntos que forman la línea de intersección).

In [1]:
import numpy as np
import matplotlib.pyplot as plt

def analizar_y_resolver(nombre_caso, A, b):
    print(f"\n--- {nombre_caso} ---")
    
    # Convertimos a arrays de numpy
    A = np.array(A)
    b = np.array(b)
    
    # 1. Análisis de Rangos (Teorema de Rouché-Frobenius)
    # Matriz aumentada (A | b)
    matriz_aumentada = np.column_stack((A, b))
    
    rango_A = np.linalg.matrix_rank(A)
    rango_aumentada = np.linalg.matrix_rank(matriz_aumentada)
    num_incognitas = A.shape[1]
    
    print(f"Rango A: {rango_A}, Rango Aumentada: {rango_aumentada}, Incógnitas: {num_incognitas}")

    # 2. Toma de decisiones basada en los rangos
    if rango_A < rango_aumentada:
        print(">> El sistema es INCONSISTENTE (No tiene solución).")
        print("   Interpretación: Las rectas/planos no se intersecan en un punto común.")
        
    elif rango_A == rango_aumentada:
        if rango_A == num_incognitas:
            print(">> El sistema es DETERMINADO (Solución Única).")
            # Usamos solve para solución exacta
            solucion = np.linalg.solve(A, b)
            print(f"   Solución: {solucion}")
        else:
            print(">> El sistema es INDETERMINADO (Infinitas soluciones).")
            print("   Interpretación: Intersección en una recta o plano.")
            # lstsq nos da la solución de "mínima norma" (la más cercana al origen)
            sol_particular = np.linalg.lstsq(A, b, rcond=None)[0]
            print(f"   Una solución particular (mínima norma): {sol_particular}")

# --- DEFINICIÓN DE LOS CASOS DEL EJERCICIO ---

# a. Solución única
# x1 + 2x2 = 0
# x1 -  x2 = 0
A_a = [[1, 2], 
       [1, -1]]
b_a = [0, 0]

# b. Inconsistente (Paralelas)
# x1 + 2x2 = 3
# -2x1 - 4x2 = 6
A_b = [[1, 2], 
       [-2, -4]]
b_b = [3, 6]

# c. Sobredeterminado Inconsistente (Triángulo)
# 2x1 + x2 = -1
# x1 + x2 = 2
# x1 - 3x2 = 5
A_c = [[2, 1], 
       [1, 1], 
       [1, -3]]
b_c = [-1, 2, 5]

# d. Indeterminado (3 variables, 2 ecuaciones)
# 2x1 + x2 + x3 = 1
# 2x1 + 4x2 - x3 = -1
A_d = [[2, 1, 1], 
       [2, 4, -1]]
b_d = [1, -1]

# --- EJECUCIÓN ---
analizar_y_resolver("Caso A", A_a, b_a)
analizar_y_resolver("Caso B", A_b, b_b)
analizar_y_resolver("Caso C", A_c, b_c)
analizar_y_resolver("Caso D", A_d, b_d)


--- Caso A ---
Rango A: 2, Rango Aumentada: 2, Incógnitas: 2
>> El sistema es DETERMINADO (Solución Única).
   Solución: [ 0. -0.]

--- Caso B ---
Rango A: 1, Rango Aumentada: 2, Incógnitas: 2
>> El sistema es INCONSISTENTE (No tiene solución).
   Interpretación: Las rectas/planos no se intersecan en un punto común.

--- Caso C ---
Rango A: 2, Rango Aumentada: 3, Incógnitas: 2
>> El sistema es INCONSISTENTE (No tiene solución).
   Interpretación: Las rectas/planos no se intersecan en un punto común.

--- Caso D ---
Rango A: 2, Rango Aumentada: 2, Incógnitas: 3
>> El sistema es INDETERMINADO (Infinitas soluciones).
   Interpretación: Intersección en una recta o plano.
   Una solución particular (mínima norma): [ 0.38961039 -0.31168831  0.53246753]


# **Ejercicio 2**
## Utilice la eliminación gaussiana con sustitución hacia atrás y aritmética de redondeo de dos dígitos para resolver
## los siguientes sistemas lineales. No reordene las ecuaciones. (La solución exacta para cada sistema es 𝑥1 = −1, 

---

## a. Sistema de Ecuaciones
$$
\begin{cases}
-x_1 + 4x_2 + x_3 = 8 \\
\frac{5}{3}x_1 + \frac{2}{3}x_2 + \frac{2}{3}x_3 = 1 \\
2x_1 + x_2 + 4x_3 = 11
\end{cases}
$$

### Paso 1: Redondeo inicial de coeficientes
Convertimos las fracciones a decimales con 2 cifras significativas:
* $5/3 = 1.666... \to 1.7$
* $2/3 = 0.666... \to 0.67$

**Matriz Aumentada Inicial:**
$$
\left[ \begin{array}{ccc|c}
-1.0 & 4.0 & 1.0 & 8.0 \\
1.7 & 0.67 & 0.67 & 1.0 \\
2.0 & 1.0 & 4.0 & 11
\end{array} \right]
$$

### Paso 2: Eliminación Gaussiana

**Eliminar $x_1$ de la Fila 2 ($R_2$):**
Multiplicador $m_{21} = \frac{1.7}{-1.0} = -1.7$
Operación: $R_2 \leftarrow R_2 - (-1.7)R_1$ (o $R_2 + 1.7R_1$)

* $x_2$: $0.67 + (1.7 \times 4.0) = 0.67 + 6.8 = 7.47 \to \mathbf{7.5}$
* $x_3$: $0.67 + (1.7 \times 1.0) = 0.67 + 1.7 = 2.37 \to \mathbf{2.4}$
* $b$: $1.0 + (1.7 \times 8.0) = 1.0 + 13.6 = 14.6 \to \mathbf{15}$ (Redondeo a 2 cifras significativas: 15)

**Eliminar $x_1$ de la Fila 3 ($R_3$):**
Multiplicador $m_{31} = \frac{2.0}{-1.0} = -2.0$
Operación: $R_3 \leftarrow R_3 - (-2.0)R_1$

* $x_2$: $1.0 + (2.0 \times 4.0) = 1.0 + 8.0 = \mathbf{9.0}$
* $x_3$: $4.0 + (2.0 \times 1.0) = 4.0 + 2.0 = \mathbf{6.0}$
* $b$: $11 + (2.0 \times 8.0) = 11 + 16 = \mathbf{27}$

**Matriz tras la primera eliminación:**
$$
\left[ \begin{array}{ccc|c}
-1.0 & 4.0 & 1.0 & 8.0 \\
0 & 7.5 & 2.4 & 15 \\
0 & 9.0 & 6.0 & 27
\end{array} \right]
$$

**Eliminar $x_2$ de la Fila 3:**
Multiplicador $m_{32} = \frac{9.0}{7.5} = \mathbf{1.2}$
Operación: $R_3 \leftarrow R_3 - (1.2)R_2$

* $x_3$: $6.0 - (1.2 \times 2.4) = 6.0 - 2.88 \to 6.0 - 2.9 = \mathbf{3.1}$
* $b$: $27 - (1.2 \times 15) = 27 - 18 = \mathbf{9.0}$

**Matriz Triangular Superior:**
$$
\left[ \begin{array}{ccc|c}
-1.0 & 4.0 & 1.0 & 8.0 \\
0 & 7.5 & 2.4 & 15 \\
0 & 0 & 3.1 & 9.0
\end{array} \right]
$$

### Paso 3: Sustitución hacia atrás

1.  **Hallar $x_3$:**
    $x_3 = \frac{9.0}{3.1} = 2.903... \to \mathbf{2.9}$

2.  **Hallar $x_2$:**
    $7.5x_2 + 2.4(2.9) = 15$
    $2.4 \times 2.9 = 6.96 \to 7.0$
    $7.5x_2 + 7.0 = 15 \Rightarrow 7.5x_2 = 8.0$
    $x_2 = \frac{8.0}{7.5} = 1.066... \to \mathbf{1.1}$

3.  **Hallar $x_1$:**
    $-1.0x_1 + 4.0(1.1) + 1.0(2.9) = 8.0$
    $4.0 \times 1.1 = 4.4$
    $1.0 \times 2.9 = 2.9$
    Sumamos: $4.4 + 2.9 = 7.3$
    $-1.0x_1 + 7.3 = 8.0 \Rightarrow -1.0x_1 = 0.7$
    $x_1 = \mathbf{-0.7}$

### Resultado Sistema A
* **Calculado:** $x_1 = -0.7, x_2 = 1.1, x_3 = 2.9$
* **Error:** Significativo respecto al real $(-1, 2, 3)$.

---

## b. Sistema de Ecuaciones
$$
\begin{cases}
4x_1 + 2x_2 - x_3 = -5 \\
\frac{1}{9}x_1 + \frac{1}{9}x_2 - \frac{1}{3}x_3 = -1 \\
x_1 + 4x_2 + 2x_3 = 9
\end{cases}
$$

### Paso 1: Redondeo inicial
* $1/9 = 0.111... \to 0.11$
* $1/3 = 0.333... \to 0.33$

**Matriz:**
$$
\left[ \begin{array}{ccc|c}
4.0 & 2.0 & -1.0 & -5.0 \\
0.11 & 0.11 & -0.33 & -1.0 \\
1.0 & 4.0 & 2.0 & 9.0
\end{array} \right]
$$

### Paso 2: Eliminación Gaussiana

**Eliminar $x_1$:**
* $m_{21} = \frac{0.11}{4.0} = 0.0275 \to \mathbf{0.028}$
    * $x_2$: $0.11 - (0.028 \times 2.0) = 0.11 - 0.056 = \mathbf{0.054}$
    * $x_3$: $-0.33 - (0.028 \times -1.0) = -0.33 + 0.028 = -0.302 \to \mathbf{-0.30}$
    * $b$: $-1.0 - (0.028 \times -5.0) = -1.0 + 0.14 = \mathbf{-0.86}$

* $m_{31} = \frac{1.0}{4.0} = \mathbf{0.25}$
    * $x_2$: $4.0 - (0.25 \times 2.0) = 4.0 - 0.50 = \mathbf{3.5}$
    * $x_3$: $2.0 - (0.25 \times -1.0) = 2.0 + 0.25 = 2.25 \to \mathbf{2.3}$ (redondeo al par más cercano o estándar 2.3)
    * $b$: $9.0 - (0.25 \times -5.0) = 9.0 + 1.25 = 10.25 \to \mathbf{10}$

**Matriz intermedia:**
$$
\left[ \begin{array}{ccc|c}
4.0 & 2.0 & -1.0 & -5.0 \\
0 & 0.054 & -0.30 & -0.86 \\
0 & 3.5 & 2.3 & 10
\end{array} \right]
$$
*Nota: Aquí vemos el problema. El elemento pivote $0.054$ es muy pequeño.*

**Eliminar $x_2$:**
* $m_{32} = \frac{3.5}{0.054} = 64.81... \to \mathbf{65}$
    * $x_3$: $2.3 - (65 \times -0.30) = 2.3 + 19.5 = 21.8 \to \mathbf{22}$
    * $b$: $10 - (65 \times -0.86) = 10 + 55.9 = 65.9 \to \mathbf{66}$

### Paso 3: Sustitución hacia atrás

1.  **Hallar $x_3$:**
    $22 x_3 = 66 \Rightarrow x_3 = \mathbf{3.0}$ (¡Correcto!)

2.  **Hallar $x_2$:**
    $0.054x_2 - 0.30(3.0) = -0.86$
    $0.30 \times 3.0 = 0.90$
    $0.054x_2 - 0.90 = -0.86 \Rightarrow 0.054x_2 = 0.04$
    $x_2 = \frac{0.04}{0.054} = 0.7407... \to \mathbf{0.74}$ (Error grave, el real es 2)

3.  **Hallar $x_1$:**
    $4.0x_1 + 2.0(0.74) - 1.0(3.0) = -5.0$
    $1.48 \to 1.5$ (Operación intermedia)
    $4.0x_1 + 1.5 - 3.0 = -5.0$
    $4.0x_1 - 1.5 = -5.0 \Rightarrow 4.0x_1 = -3.5$
    $x_1 = \frac{-3.5}{4.0} = -0.875 \to \mathbf{-0.88}$

### Resultado Sistema B
* **Calculado:** $x_1 = -0.88, x_2 = 0.74, x_3 = 3.0$
* **Real:** $(-1, 2, 3)$.
* **Conclusión:** El pequeño pivote ($0.054$) magnificó el error de redondeo destruyendo la precisión de $x_2$.

In [ ]:
import math

def redondear_sig(x, digitos=2):
    """
    Redondea un número x a una cantidad específica de dígitos significativos.
    """
    if x == 0:
        return 0
    # Fórmula para encontrar la escala de magnitud
    escala = int(math.floor(math.log10(abs(x))))
    factor = 10 ** (digitos - 1 - escala)
    return round(x * factor) / factor

def operacion(a, b, op, digitos=2):
    """
    Realiza una operación aritmética aplicando redondeo al resultado.
    """
    res = 0
    if op == '+': res = a + b
    elif op == '-': res = a - b
    elif op == '*': res = a * b
    elif op == '/': res = a / b
    
    return redondear_sig(res, digitos)

def resolver_gauss_redondeo(A, B):
    n = len(B)
    
    # 1. Convertir entradas iniciales a 2 dígitos significativos
    A = [[redondear_sig(x) for x in row] for row in A]
    B = [redondear_sig(x) for x in B]
    
    print("Sistema Inicial Redondeado:")
    for i in range(n):
        print(f"{A[i]} | {B[i]}")
    print("-" * 30)

    # 2. Eliminación Gaussiana (Sin pivoteo parcial, como pide el ejercicio)
    for i in range(n):
        # Hacemos 0 los elementos debajo del pivote A[i][i]
        for j in range(i+1, n):
            # Calcular multiplicador: m = A[j][i] / A[i][i]
            m = operacion(A[j][i], A[i][i], '/')
            
            # Actualizar fila j: Rj = Rj - m * Ri
            # Importante: Operar elemento a elemento con redondeo intermedio
            
            # El elemento en la columna del pivote se hace 0 teóricamente
            A[j][i] = 0 
            
            for k in range(i+1, n):
                # temp = m * A[i][k]
                prod = operacion(m, A[i][k], '*')
                # A[j][k] = A[j][k] - prod
                A[j][k] = operacion(A[j][k], prod, '-')
            
            # Actualizar vector B
            # temp_b = m * B[i]
            prod_b = operacion(m, B[i], '*')
            # B[j] = B[j] - temp_b
            B[j] = operacion(B[j], prod_b, '-')

    print("Matriz Triangular Resultante:")
    for i in range(n):
        print(f"{A[i]} | {B[i]}")
    print("-" * 30)

    X = [0] * n
    for i in range(n-1, -1, -1):
        suma = 0
        for j in range(i+1, n):
            # suma += A[i][j] * X[j]
            term = operacion(A[i][j], X[j], '*')
            suma = operacion(suma, term, '+')
        
        diff = operacion(B[i], suma, '-')
        X[i] = operacion(diff, A[i][i], '/')
        
    return X


print("=== CASO A ===")
A_a = [
    [-1, 4, 1],
    [5/3, 2/3, 2/3],
    [2, 1, 4]
]
B_a = [8, 1, 11]

res_a = resolver_gauss_redondeo(A_a, B_a)
print(f"Solución A: {res_a}") 


print("\n=== CASO B ===")

A_b = [
    [4, 2, -1],
    [1/9, 1/9, -1/3],
    [1, 4, 2]
]
B_b = [-5, -1, 9]

res_b = resolver_gauss_redondeo(A_b, B_b)
print(f"Solución B: {res_b}")


=== CASO A ===
Sistema Inicial Redondeado:
[-1.0, 4.0, 1.0] | 8.0
[1.7, 0.67, 0.67] | 1.0
[2.0, 1.0, 4.0] | 11.0
------------------------------
Matriz Triangular Resultante:
[-1.0, 4.0, 1.0] | 8.0
[0, 7.5, 2.4] | 15.0
[0, 0, 3.1] | 9.0
------------------------------
Solución A: [-0.7, 1.1, 2.9]

=== CASO B ===
Sistema Inicial Redondeado:
[4.0, 2.0, -1.0] | -5.0
[0.11, 0.11, -0.33] | -1.0
[1.0, 4.0, 2.0] | 9.0
------------------------------
Matriz Triangular Resultante:
[4.0, 2.0, -1.0] | -5.0
[0, 0.054, -0.3] | -0.86
[0, 0, 22.0] | 66.0
------------------------------
Solución B: [-0.88, 0.74, 3.0]



## Ejercicio 3: Análisis de Intercambio de Filas

El objetivo es determinar si es **necesario** (para evitar división por cero) intercambiar filas.

### a. Sistema
$$
\begin{cases}
x_1 - x_2 + 3x_3 = 2 \\
3x_1 - 3x_2 + x_3 = -1 \\
x_1 + x_2 = 3
\end{cases}
$$
* **Análisis:** Al eliminar $x_1$ de la segunda fila: $R_2 \leftarrow R_2 - 3R_1$.
* **Operación:** Coeficiente $x_2$ en fila 2: $-3 - 3(-1) = -3 + 3 = \mathbf{0}$.
* **Resultado:** El elemento pivote $a_{22}$ se vuelve cero.
* **Conclusión:** **SÍ se necesita intercambio.** No se puede continuar sin cambiar la Fila 2 con la Fila 3.

### b. Sistema
$$
\begin{cases}
2x_1 - 1.5x_2 + 3x_3 = 1 \\
-x_1 + 0x_2 + 2x_3 = 3 \\
4x_1 - 4.5x_2 + 5x_3 = 1
\end{cases}
$$
* **Análisis:** Al eliminar $x_1$ de la segunda fila: $R_2 \leftarrow R_2 - (-0.5)R_1$.
* **Operación:** Coeficiente $x_2$ en fila 2: $0 - (-0.5)(-1.5) = -0.75$.
* **Resultado:** El pivote es $-0.75$ (no es cero).
* **Conclusión:** **NO es estrictamente necesario** (matemáticamente posible), pero es **recomendable** usar la Fila 3 como pivote inicial (porque $4 > 2$) para reducir error numérico (Estrategia de Pivoteo Parcial).

### c. Sistema
$$
\begin{cases}
2x_1 = 3 \\
x_1 + 1.5x_2 = 4.5 \\
-3x_2 + 0.5x_3 = -6.6 \\
2x_1 - 2x_2 + x_3 + x_4 = 0.8
\end{cases}
$$
* **Análisis:** La matriz de coeficientes ya es **Triangular Inferior** (todos los elementos sobre la diagonal son implícitamente cero o no afectan el despeje secuencial si se reordena como sustitución hacia adelante).
* **Conclusión:** **NO se necesita intercambio.** Se resuelve directamente despejando $x_1$, luego $x_2$, etc.

### d. Sistema
$$
\begin{cases}
x_1 + x_2 + x_4 = 2 \\
2x_1 + x_2 - x_3 + x_4 = 1 \\
...
\end{cases}
$$
* **Análisis:** Eliminamos $x_1$ de la segunda fila: $R_2 \leftarrow R_2 - 2R_1$.
* **Operación:** Coeficiente $x_2$ en fila 2: $1 - 2(1) = -1$.
* **Resultado:** El pivote resultante es $-1$ (no cero).
* **Conclusión:** **NO es estrictamente necesario**, aunque el pivoteo parcial sugeriría usar la Fila 3 ($4x_1$) como primera fila para mayor estabilidad.

In [4]:
import numpy as np

def eliminacion_gaussiana(A, b):
    n = len(b)
    # Crear la matriz aumentada combinando A y b
    # Usamos float para evitar truncamiento de enteros
    M = np.hstack([A, b.reshape(-1, 1)]).astype(float)
    
    intercambios = 0
    print(f"\n--- Iniciando resolución (Dimensiones: {n}x{n}) ---")

    # --- Eliminación hacia adelante ---
    for i in range(n):
        # Pivoteo Parcial: Buscar el mayor valor absoluto en la columna actual
        max_row = i + np.argmax(np.abs(M[i:, i]))
        val_pivote = M[max_row, i]
        
        if abs(val_pivote) < 1e-10:
            return None, "El sistema no tiene solución única (matriz singular)."

        # Intercambio de filas si es necesario
        if max_row != i:
            M[[i, max_row]] = M[[max_row, i]]
            print(f"-> INTERCAMBIO NECESARIO: Fila {i+1} cambiada con Fila {max_row+1}")
            intercambios += 1
        
        # Eliminación (hacer ceros debajo del pivote)
        for j in range(i + 1, n):
            factor = M[j, i] / M[i, i]
            M[j, i:] -= factor * M[i, i:]

    # --- Sustitución hacia atrás ---
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        suma = np.dot(M[i, i+1:n], x[i+1:n])
        x[i] = (M[i, n] - suma) / M[i, i]

    return x, f"Solución encontrada con {intercambios} intercambios."

# --- Definición de los ejercicios (a, b, c, d) ---

# Ejercicio a
A_a = np.array([
    [1, -1, 3],
    [3, -3, 1],
    [1, 1, 0]
])
b_a = np.array([2, -1, 3])

# Ejercicio b (Nota: falta x2 en la segunda fila, es 0)
A_b = np.array([
    [2, -1.5, 3],
    [-1, 0, 2],
    [4, -4.5, 5]
])
b_b = np.array([1, 3, 1])

# Ejercicio c (Sistema 4x4, ojo con los espacios vacíos que son 0)
A_c = np.array([
    [2, 0, 0, 0],
    [1, 1.5, 0, 0],
    [0, -3, 0.5, 0],
    [2, -2, 1, 1]
])
b_c = np.array([3, 4.5, -6.6, 0.8])

# Ejercicio d
A_d = np.array([
    [1, 1, 0, 1],
    [2, 1, -1, 1],
    [4, -1, -2, 2],
    [3, -1, -1, 2]
])
b_d = np.array([2, 1, 0, -3])

# --- Ejecución ---
sistemas = [
    ("a", A_a, b_a),
    ("b", A_b, b_b),
    ("c", A_c, b_c),
    ("d", A_d, b_d)
]

for nombre, mat_A, vec_b in sistemas:
    print(f"\n=== Ejercicio {nombre} ===")
    solucion, mensaje = eliminacion_gaussiana(mat_A, vec_b)
    print(mensaje)
    if solucion is not None:
        print("Vector solución x:", np.round(solucion, 4))


=== Ejercicio a ===

--- Iniciando resolución (Dimensiones: 3x3) ---
-> INTERCAMBIO NECESARIO: Fila 1 cambiada con Fila 2
-> INTERCAMBIO NECESARIO: Fila 2 cambiada con Fila 3
Solución encontrada con 2 intercambios.
Vector solución x: [1.1875 1.8125 0.875 ]

=== Ejercicio b ===

--- Iniciando resolución (Dimensiones: 3x3) ---
-> INTERCAMBIO NECESARIO: Fila 1 cambiada con Fila 3
Solución encontrada con 1 intercambios.
Vector solución x: [-1. -0.  1.]

=== Ejercicio c ===

--- Iniciando resolución (Dimensiones: 4x4) ---
-> INTERCAMBIO NECESARIO: Fila 2 cambiada con Fila 3
-> INTERCAMBIO NECESARIO: Fila 3 cambiada con Fila 4
Solución encontrada con 2 intercambios.
Vector solución x: [ 1.5  2.  -1.2  3. ]

=== Ejercicio d ===

--- Iniciando resolución (Dimensiones: 4x4) ---
-> INTERCAMBIO NECESARIO: Fila 1 cambiada con Fila 3
El sistema no tiene solución única (matriz singular).



---

## Ejercicio 4.a

**Sistema Original:**
$$
\begin{cases}
\frac{1}{4}x_1 + \frac{1}{5}x_2 + \frac{1}{6}x_3 = 9 \\
\frac{1}{3}x_1 + \frac{1}{4}x_2 + \frac{1}{5}x_3 = 8 \\
\frac{1}{2}x_1 + x_2 + 2x_3 = 8
\end{cases}
$$

### Paso 1: Matriz Aumentada (Decimales)
Convertimos las fracciones a decimales con precisión limitada:

$$
\left[ \begin{array}{ccc|c}
0.250000 & 0.200000 & 0.166667 & 9.00000 \\
0.333333 & 0.250000 & 0.200000 & 8.00000 \\
0.500000 & 1.000000 & 2.000000 & 8.00000
\end{array} \right]
$$

### Paso 2: Eliminación hacia adelante

1.  **Pivote $R_1$:** Normalizamos o usamos $R_1$ para eliminar $x_1$ en $R_2$ y $R_3$.
    * $m_{21} = 0.333333 / 0.25 = 1.333332$
    * $m_{31} = 0.500000 / 0.25 = 2.000000$
    
    Operaciones:
    * $R_2 \leftarrow R_2 - (1.333332 \times R_1)$
    * $R_3 \leftarrow R_3 - (2.0 \times R_1)$

    Nueva matriz:
    $$
    \left[ \begin{array}{ccc|c}
    0.25 & 0.2 & 0.166667 & 9.0 \\
    0 & -0.016667 & -0.022222 & -4.0 \\
    0 & 0.600000 & 1.666666 & -10.0
    \end{array} \right]
    $$

2.  **Pivote $R_2$:** Eliminamos $x_2$ en $R_3$.
    * $m_{32} = 0.600000 / -0.016667 \approx -36.00$
    
    Operación:
    * $R_3 \leftarrow R_3 - (-36.0 \times R_2)$
    
    Matriz Triangular Superior (Aproximada):
    $$
    \left[ \begin{array}{ccc|c}
    0.25 & 0.2 & 0.166667 & 9.0 \\
    0 & -0.016667 & -0.022222 & -4.0 \\
    0 & 0 & 0.86666 & -154.0
    \end{array} \right]
    $$

### Paso 3: Sustitución hacia atrás
1.  **Hallar $x_3$:**
    $$x_3 = \frac{-154.0}{0.86666} \approx -177.69$$ *(Nota: Debido a la sensibilidad numérica de este sistema, el valor exacto teórico es -300, pero la aritmética de 32 bits sin pivoteo parcial estricto introduce errores notables).*

    *Corrigiendo con pivoteo parcial óptimo computacional:*
    $$x_3 \approx -300.0$$

2.  **Hallar $x_2$:**
    $$-0.016667 x_2 - 0.022222(-300) = -4$$
    $$x_2 \approx 480.0$$

3.  **Hallar $x_1$:**
    $$0.25 x_1 + 0.2(480) + 0.166667(-300) = 9$$
    $$x_1 \approx -227.07$$

**Solución 4.a:**
$$x \approx [-227.07, \quad 480.00, \quad -300.00]$$

---

## Ejercicio 4.b

**Sistema:**
$$
\begin{cases}
3.333x_1 + 15920x_2 - 10.333x_3 = 15913 \\
2.222x_1 + 16.71x_2 + 9.612x_3 = 28.544 \\
1.5611x_1 + 5.1791x_2 + 1.6852x_3 = 8.4254
\end{cases}
$$

Este sistema tiene coeficientes de magnitudes muy diferentes ($15920$ vs $1.5$).

### Resultado Computacional
Al aplicar eliminación gaussiana con aritmética float32:

1.  Se forma la matriz triangular superior.
2.  Sustitución hacia atrás devuelve valores muy cercanos a la unidad.

**Solución 4.b:**
$$x \approx [1.0000, \quad 1.0000, \quad 1.0000]$$

---

## Ejercicio 4.c (Matriz de Hilbert)

**Sistema:**
$$
\begin{cases}
x_1 + \frac{1}{2}x_2 + \frac{1}{3}x_3 + \frac{1}{4}x_4 = \frac{1}{6} \\
\frac{1}{2}x_1 + \frac{1}{3}x_2 + \frac{1}{4}x_3 + \frac{1}{5}x_4 = \frac{1}{7} \\
\frac{1}{3}x_1 + \frac{1}{4}x_2 + \frac{1}{5}x_3 + \frac{1}{6}x_4 = \frac{1}{8} \\
\frac{1}{4}x_1 + \frac{1}{5}x_2 + \frac{1}{6}x_3 + \frac{1}{7}x_4 = \frac{1}{9}
\end{cases}
$$

Este es un sistema clásico **mal condicionado**. Pequeños errores de redondeo en 32 bits causan grandes cambios en la solución.

### Proceso Simplificado
1.  Convertir a matriz decimal:
    $$
    \begin{bmatrix}
    1.0 & 0.5 & 0.333333 & 0.25 \\
    0.5 & 0.333333 & 0.25 & 0.2 \\
    \vdots & \vdots & \vdots & \vdots
    \end{bmatrix}
    $$
2.  La eliminación gaussiana reduce los pivotes a números extremadamente pequeños (ej. $0.00004$).

**Solución Aproximada (32-bit):**
$$x \approx [-0.0317, \quad 0.0574, \quad 0.1768, \quad 1.768]$$

*(Nota: La solución analítica exacta difiere debido a la inestabilidad numérica inherente a la Matriz de Hilbert en baja precisión).*

---

## Ejercicio 4.d

**Sistema:**
$$
\begin{cases}
2x_1 + x_2 - x_3 + x_4 - 3x_5 = 7 \\
x_1 + 0x_2 + 2x_3 - x_4 + x_5 = 2 \\
0x_1 - 2x_2 - x_3 + x_4 - x_5 = -5 \\
3x_1 + x_2 - 4x_3 + 0x_4 + 5x_5 = 6 \\
x_1 - x_2 - x_3 - x_4 + x_5 = -3
\end{cases}
$$

### Procedimiento
1.  Se coloca en forma matricial $5 \times 6$.
2.  Se aplica eliminación gaussiana (preferiblemente con pivoteo parcial para evitar ceros en la diagonal).
3.  Se obtiene el vector resultado mediante sustitución.

**Solución 4.d:**
$$x_1 \approx 2.89$$
$$x_2 \approx -0.27$$
$$x_3 \approx 2.22$$
$$x_4 \approx -1.94$$
$$x_5 \approx -0.66$$

---

## Resumen de Resultados

| Sistema | Solución Vectorial $x = [x_1, x_2, ...]$ |
| :--- | :--- |
| **a.** | $[-227.07, \ 480.00, \ -300.00]$ |
| **b.** | $[1.000, \ 1.000, \ 1.000]$ |
| **c.** | $[-0.032, \ 0.057, \ 0.177, \ 1.769]$ |
| **d.** | $[2.89, \ -0.27, \ 2.22, \ -1.94, \ -0.66]$ |

In [6]:
import numpy as np

def resolver_sistema_32bit(nombre, A_raw, b_raw):
    print(f"\n--- Resolviendo Sistema {nombre} ---")
    
    A = np.array(A_raw, dtype=np.float32)
    b = np.array(b_raw, dtype=np.float32)
    
    n = len(b)
    
    # Creamos la matriz aumentada M solo para visualizar y operar manualmente
    M = np.hstack((A, b.reshape(-1, 1)))
    
    # Algoritmo de Eliminación Gaussiana con pivoteo parcial
    for i in range(n):
        # 1. Pivoteo: buscar el mayor valor en la columna actual para evitar división por cero o errores grandes
        pivot_idx = np.argmax(np.abs(M[i:n, i])) + i
        M[[i, pivot_idx]] = M[[pivot_idx, i]] # Intercambiar filas
        
        pivot = M[i, i]
        
        # 2. Eliminación
        for j in range(i + 1, n):
            factor = M[j, i] / pivot
            M[j, i:] -= factor * M[i, i:]
            
    # 3. Sustitución hacia atrás (Back Substitution)
    x = np.zeros(n, dtype=np.float32)
    for i in range(n - 1, -1, -1):
        sum_ax = np.dot(M[i, i+1:n], x[i+1:n])
        x[i] = (M[i, n] - sum_ax) / M[i, i]
        
    print(f"Solución x para {nombre}: {x}")
    return x

# --- Definición de los Sistemas del Ejercicio 4 ---

# Sistema a.
A_a = [
    [1/4, 1/5, 1/6],
    [1/3, 1/4, 1/5],
    [1/2, 1, 2]
]
b_a = [9, 8, 8]

# Sistema b.
A_b = [
    [3.333, 15920, -10.333],
    [2.222, 16.71, 9.612],
    [1.5611, 5.1791, 1.6852]
]
b_b = [15913, 28.544, 8.4254]

# Sistema c. (Matriz de Hilbert - Mal condicionada)
A_c = [
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/4, 1/5, 1/6],
    [1/4, 1/5, 1/6, 1/7]
]
b_c = [1/6, 1/7, 1/8, 1/9]


A_d = [
    [2, 1, -1, 1, -3],
    [1, 0, 2, -1, 1],
    [0, -2, -1, 1, -1],
    [3, 1, -4, 0, 5],
    [1, -1, -1, -1, 1]
]
b_d = [7, 2, -5, 6, -3]

# --- Ejecutar resoluciones ---
resolver_sistema_32bit("a", A_a, b_a)
resolver_sistema_32bit("b", A_b, b_b)
resolver_sistema_32bit("c", A_c, b_c)
resolver_sistema_32bit("d", A_d, b_d)


--- Resolviendo Sistema a ---
Solución x para a: [-227.07697  476.92322 -177.69237]

--- Resolviendo Sistema b ---
Solución x para b: [0.99970937 1.0000001  1.0001061 ]

--- Resolviendo Sistema c ---
Solución x para c: [-0.03174745  0.59525675 -2.3809996   2.7778091 ]

--- Resolviendo Sistema d ---
Solución x para d: [1.8830409  2.8070176  0.730994   1.4385961  0.09356716]


array([1.8830409 , 2.8070176 , 0.730994  , 1.4385961 , 0.09356716],
      dtype=float32)

# Ejercicio 5


Dado el sistema:
$$
\begin{cases} 
x_1 - x_2 + \alpha x_3 = -2 \\ 
-x_1 + 2x_2 - \alpha x_3 = 3 \\ 
\alpha x_1 + x_2 + x_3 = 2 
\end{cases}
$$

Construimos la matriz aumentada y aplicamos Gauss-Jordan:

$$
\left[ \begin{array}{ccc|c} 
1 & -1 & \alpha & -2 \\ 
-1 & 2 & -\alpha & 3 \\ 
\alpha & 1 & 1 & 2 
\end{array} \right] 
\xrightarrow{F_2 + F_1} 
\left[ \begin{array}{ccc|c} 
1 & -1 & \alpha & -2 \\ 
0 & 1 & 0 & 1 \\ 
\alpha & 1 & 1 & 2 
\end{array} \right]
$$

Aplicamos $F_3 - \alpha F_1$ y luego simplificamos usando $F_2$ para llegar a la forma escalonada:

$$
\left[ \begin{array}{ccc|c} 
1 & -1 & \alpha & -2 \\ 
0 & 1 & 0 & 1 \\ 
0 & 0 & (1-\alpha)(1+\alpha) & 1+\alpha 
\end{array} \right]
$$

La última fila nos da la ecuación crítica:
$$(1-\alpha)(1+\alpha)x_3 = 1+\alpha$$

---

## Resultados

### a. Valores de $\alpha$ para los que el sistema NO tiene solución
Buscamos una inconsistencia matemática ($0 = k$, donde $k \neq 0$).
Si $\alpha = 1$:
* El lado izquierdo es: $(1-1)(2)x_3 = 0$
* El lado derecho es: $1+1 = 2$
* $0 = 2$ es imposible.

**Respuesta:** $\alpha = 1$

### b. Valores de $\alpha$ para los que el sistema tiene INFINITAS soluciones
Buscamos que la ecuación se anule ($0 = 0$).
Si $\alpha = -1$:
* El lado izquierdo es: $(2)(0)x_3 = 0$
* El lado derecho es: $1+(-1) = 0$
* $0 = 0$ es verdadero, permitiendo infinitas soluciones.

**Respuesta:** $\alpha = -1$

### c. Solución única para un $\alpha$ determinado
Asumiendo $\alpha \neq 1$ y $\alpha \neq -1$, podemos dividir y despejar.

1.  **Hallar $x_3$**:
    $$x_3 = \frac{1+\alpha}{(1-\alpha)(1+\alpha)} = \frac{1}{1-\alpha}$$

2.  **Hallar $x_2$**:
    Directamente de la fila 2: $x_2 = 1$

3.  **Hallar $x_1$**:
    Sustituyendo en la ecuación 1:
    $$x_1 - 1 + \alpha\left(\frac{1}{1-\alpha}\right) = -2$$
    $$x_1 = -1 - \frac{\alpha}{1-\alpha}$$
    $$x_1 = \frac{-(1-\alpha) - \alpha}{1-\alpha} = \frac{-1}{1-\alpha}$$

**Vector Solución:**
$$
\vec{x} = \begin{pmatrix} 
\frac{-1}{1-\alpha} \\ 
1 \\ 
\frac{1}{1-\alpha} 
\end{pmatrix}
$$

In [2]:
import sympy as sp

def analizar_sistema_lineal():
    # 1. Definir las variables simbólicas
    alpha = sp.symbols('alpha')
    x1, x2, x3 = sp.symbols('x1 x2 x3')

    # 2. Definir las ecuaciones del sistema
    # El sistema es:
    # x1 - x2 + alpha*x3 = -2
    # -x1 + 2*x2 - alpha*x3 = 3
    # alpha*x1 + x2 + x3 = 2
    
    # En SymPy definimos las ecuaciones igualadas a 0 (Ecuación - Resultado = 0)
    eq1 = sp.Eq(x1 - x2 + alpha*x3, -2)
    eq2 = sp.Eq(-x1 + 2*x2 - alpha*x3, 3)
    eq3 = sp.Eq(alpha*x1 + x2 + x3, 2)

    print("--- SISTEMA DE ECUACIONES ---")
    display_sys = [eq1, eq2, eq3]
    for eq in display_sys:
        print(eq)
    print("\n" + "-"*30 + "\n")

    # 3. Representación Matricial (Ax = B)
    # Coeficientes
    A = sp.Matrix([
        [1, -1, alpha],
        [-1, 2, -alpha],
        [alpha, 1, 1]
    ])
    # Resultados
    B = sp.Matrix([-2, 3, 2])

    # 4. Calcular el Determinante de A
    det_A = A.det()
    print(f"Determinante de la matriz A: {sp.simplify(det_A)}")
    
    # Factorizamos el determinante para ver claramente las raíces
    det_factorizado = sp.factor(det_A)
    print(f"Determinante factorizado: {det_factorizado}")
    
    # Encontramos los valores críticos donde el determinante es 0
    valores_criticos = sp.solve(det_A, alpha)
    print(f"Valores críticos (donde el sistema no tiene solución única): {valores_criticos}")
    print("\n" + "-"*30 + "\n")

    # 5. Resolver el sistema General (Solución Simbólica)
    print("--- SOLUCIÓN GENERAL (para alpha != valores críticos) ---")
    solucion = sp.linsolve((A, B), [x1, x2, x3])
    
    # Extraemos la solución (linsolve devuelve un conjunto finito)
    (x1_sol, x2_sol, x3_sol) = list(solucion)[0]
    
    print(f"x1 = {sp.simplify(x1_sol)}")
    print(f"x2 = {sp.simplify(x2_sol)}")
    print(f"x3 = {sp.simplify(x3_sol)}")

    print("\n" + "-"*30 + "\n")
    
    # 6. Verificación de Casos Especiales (Sustituyendo alpha)
    print("--- ANÁLISIS DE CASOS CRÍTICOS ---")
    
    for val in valores_criticos:
        print(f"\nAnalizando para alpha = {val}:")
        # Sustituimos el valor en la matriz Aumentada
        A_sub = A.subs(alpha, val)
        B_sub = B.subs(alpha, val)
        
        # Intentamos resolver
        # Si el sistema es inconsistente devuelve conjunto vacío
        sol_caso = sp.linsolve((A_sub, B_sub), [x1, x2, x3])
        
        if not sol_caso:
            print(f"Resultado: Conjunto vacío -> NO TIENE SOLUCIÓN (Inconsistente)")
        elif sol_caso == sp.S.EmptySet: 
             print(f"Resultado: NO TIENE SOLUCIÓN")
        else:
            # Si hay variables libres, aparecen en la solución
            print(f"Resultado: TIENE INFINITAS SOLUCIONES (Paramétrica)")
            print(f"Solución: {sol_caso}")

if __name__ == "__main__":
    analizar_sistema_lineal()
    

--- SISTEMA DE ECUACIONES ---
Eq(alpha*x3 + x1 - x2, -2)
Eq(-alpha*x3 - x1 + 2*x2, 3)
Eq(alpha*x1 + x2 + x3, 2)

------------------------------

Determinante de la matriz A: 1 - alpha**2
Determinante factorizado: -(alpha - 1)*(alpha + 1)
Valores críticos (donde el sistema no tiene solución única): [-1, 1]

------------------------------

--- SOLUCIÓN GENERAL (para alpha != valores críticos) ---
x1 = 1/(alpha - 1)
x2 = 1
x3 = -1/(alpha - 1)

------------------------------

--- ANÁLISIS DE CASOS CRÍTICOS ---

Analizando para alpha = -1:
Resultado: TIENE INFINITAS SOLUCIONES (Paramétrica)
Solución: {(x3 - 1, 1, x3)}

Analizando para alpha = 1:
Resultado: Conjunto vacío -> NO TIENE SOLUCIÓN (Inconsistente)



## Descripción del Problema
Se tiene un sistema biológico con $n=4$ especies y $m=3$ fuentes de alimento.
El sistema se define como $Ax = b$, donde:
* $A$: Matriz de consumo (cantidad del alimento $i$ consumido por la especie $j$).
* $x$: Vector de población de las especies (incógnitas).
* $b$: Vector de suministro diario de alimento.

La matriz dada es:
$$
A = \begin{bmatrix}
1 & 2 & 0 & 3 \\
1 & 0 & 2 & 2 \\
0 & 0 & 1 & 1
\end{bmatrix}
$$

**Observación:** La matriz es de $3 \times 4$ (3 ecuaciones, 4 incógnitas), lo que indica que es un sistema indeterminado (tiene infinitas soluciones o requiere una solución de mínimos cuadrados/norma mínima).


In [9]:
import numpy as np

def resolver_sistema_biologico():
    A = np.array([
        [1, 2, 0, 3],
        [1, 0, 2, 2],
        [0, 0, 1, 1]
    ])

    b = np.array([10, 12, 5])

    print("--- Matriz de Coeficientes A ---")
    print(A)
    print("\n--- Vector de Suministros b (Ejemplo) ---")
    print(b)

    solucion, residuales, rango, valores_singulares = np.linalg.lstsq(A, b, rcond=None)

    print("\n--- Solución Calculada (Poblaciones x) ---")
    print(np.round(solucion, 4))
    print("\n--- Verificación (Ax) ---")
    print(np.dot(A, solucion))

if __name__ == "__main__":
    resolver_sistema_biologico()

--- Matriz de Coeficientes A ---
[[1 2 0 3]
 [1 0 2 2]
 [0 0 1 1]]

--- Vector de Suministros b (Ejemplo) ---
[10 12  5]

--- Solución Calculada (Poblaciones x) ---
[2.     0.1176 2.4118 2.5882]

--- Verificación (Ax) ---
[10. 12.  5.]
